config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  root 'recipes#index'

  get 'welcome/index'

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :equipments
  has_many :instructions
  has_many :ingredients

  accepts_nested_attributes_for :equipments, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :instructions, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :ingredients, :reject_if => :all_blank, :allow_destroy => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :prep, :cook, :user_id, equipments_attributes: [:id, :name, :_destroy], ingredients_attributes: [:id, :name, :quantity, :_destroy], instructions_attributes: [:id, :description, :_destroy])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>MealMaker</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container-fluid">
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
			<%= yield %>
		</div>
	</body>
</html>

app/views/recipes/_equipment_fields.html.erb
<div class="nested-fields">
	<%= f.input :name %>
	<%= link_to_remove_association "remove equipment", f, class: "btn btn-danger" %>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe, html: {multipart: true} ) do |f| %>
<%= f.error_notification %>
<div class="row">
  <div class="col-sm-3 form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :prep %>
    <%= f.input :cook %>
    <%#= f.association :user %>
    
  </div>
  <div id="equipment">
    <div class="col-sm-3">
      <%= f.simple_fields_for :equipments do |equipment_form| %>
      <%= render "equipment_fields", :f => equipment_form %>
      <% end %>
      <div class="links">
        <%= link_to_add_association "add equipment", f, :equipments, class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <div id=" ingredients">
    <div class="col-sm-3">
      <%= f.simple_fields_for :ingredients do |ingredient_form| %>
      <%= render "ingredient_fields", :f => ingredient_form %>
      <% end %>
      <div class="links">
        <%= link_to_add_association "add ingredient", f, :ingredients, class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <div id=" instructions">
    <div class="col-sm-3">
      <%= f.simple_fields_for :instructions do |instruction_form| %>
      <%= render "instruction_fields", :f => instruction_form %>
      <% end %>
      <div class="links">
        <%= link_to_add_association "add instructions", f, :instructions, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>
<div class=" form-actions">
  <%= f.button :submit, class: "btn btn-default" %>
</div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
	<%= f.input :name %>
	<%= f.input :quantity %>
	<%= link_to_remove_association "remove ingredient", f, class: "btn btn-danger" %>
</div>

app/views/recipes/_instruction_fields.html.erb
<div class="nested-fields">
	<%= f.input :description %>
	<%= link_to_remove_association "remove instruction", f, class: "btn btn-danger" %>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "sign in", new_user_session_path %>
<%= link_to "logout", destroy_user_session_path, method: :delete %>
<h1>Listing Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Prep</th>
      <th>Cook</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.prep %></td>
        <td><%= recipe.cook %></td>
        <td><%= recipe.user %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Prep:</strong>
  <%= @recipe.prep %>
</p>

<p>
  <strong>Cook:</strong>
  <%= @recipe.cook %>
</p>

<p>
  <strong>User:</strong>
  <%= @recipe.user %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>